### ISSUE TITLE
Styles and icon parameters are ignored

### ISSUE THREAD

**Issue by leonbotros** [jobisoft/tb-remplates#16]
First of all, thanks for making this API. It's neat.

I do however have a small issue with the styling of the notification. When I run the example I do not get a notification that is styled according to the API call containing this snippet:
```javascript
  style: {
      "color": "blue",
      "font-weight": "bold",
      "font-style": "italic",
      "background-color": "green",
    },
```
Also changing the icon does not have any effect. In both cases I end up with the styles and icon defined by the priority.
Tested with Thunderbird 91.5.0.

**Comment by jobisoft** [comment]
I re-added support for custom icons in https://github.com/jobisoft/notificationbar-API/commit/772e00080e3a782bd6a52a0b489bec1cb001d075 (for TB128+).

I cannot confirm styles not working. Since https://github.com/jobisoft/notificationbar-API/commit/8b0e9a3f6310f97614cd49252da991eca11560fc the example is using your styles and it works:

![image](https://github.com/user-attachments/assets/e4815b20-7376-44a3-9ef3-277ebec4bead)
